---
- name: "Create DNS zone"
  ansible.builtin.uri:
    return_content: yes
    validate_certs: false
    url: "{{ vault_url }}/api/v1/servers/{{ pdns_server_id }}/zones"
    method: PUT
    status_code: 201
    body_format: json
    body:
      zone:
        name:
    headers:
      X-API-Key: "{{ pdns_pwd }}"
  register: pdns_zone_created_info
  delegate_to: "{{ pdns_api_executor }}"