---
- name: Include podman pod profile
  include_vars:
    file: vars/powerdns-server.yaml

- name: Creates directory
  ansible.builtin.file:
    path: {{ powerdns_conf_host_cert_path }}powerdns_conf_host_cert_path
    state: directory

- name: Request certificates from vault server for harbor service
  ansible.builtin.include_role:
    name: install-configure-vault 
  vars:
    vault_gen_cert: true
    vault_install_ca_cert: true
    vault_gen_cert_fqdn: "{{ ansible_fqdn }}"
    vault_gen_cert_ip_sans: "{{ ansible_default_ipv4.address }}" 
    vault_gen_cert_install: true # true for installing cert directly to the path 
    vault_gen_cert_install_pub_path: "{{ powerdns_conf_host_cert_path }}/cert.crt"
    vault_gen_cert_install_priv_path: "{{ powerdns_conf_host_cert_path }}/cert.key"
    vault_gen_cert_install_ca_path: "{{ powerdns_conf_host_cert_path }}/ca.crt"
  when: vault_cert | bool

- name: Start podman deployment as root
  become: yes
  block:
  - name: Deploy pdns server stack
    include_role:
      name: deploy-podman-pod
    vars:
      permanent: true

# - name: "Wait for {{ ldap_server_uri }} is ready - check every 5 seconds"
#   shell: "curl --insecure -i {{ ldap_kind }}://{{ ldap_server_uri }}"
#   retries: 60
#   register: ldap_status
#   until: ldap_status.stdout.find("DN:") != -1
#   delay: 5