---
- name: Install PowerDNS /w pod profile
  include_tasks: install-powerdns.yaml
  when: powerdns_install | bool

- name: Create or remove DNS (RRSet) record
  include_tasks: create_dns_record.yaml
  when: pdns_create_record is defined
  with_items:
  - "{{ pdns_create_record }}"